// resources/js/Pages/Suppliers/Edit.jsx
import { useForm, Link } from '@inertiajs/react';

export default function SuppliersEdit({ title, supplier }) {
    const form = useForm(supplier ? {
        id: supplier.id || null,
        suppliername: supplier.suppliername || '',
        email: supplier.email || '',
        address: supplier.address || '',
        telno: supplier.telno || '',
        cellno: supplier.cellno || '',
        accreditation: supplier.accreditation || '',
        suppliertype: supplier.suppliertype || '',
        comcategory: supplier.comcategory || '',
        payterms: supplier.payterms || '',
        contactname: supplier.contactname || '',
        designation: supplier.designation || '',
        department: supplier.department || '',
        remarks: supplier.remarks || '',
    } : {
        id: null,
        suppliername: '',
        email: '',
        address: '',
        telno: '',
        cellno: '',
        accreditation: '',
        suppliertype: '',
        comcategory: '',
        payterms: '',
        contactname: '',
        designation: '',
        department: '',
        remarks: '',
    });

    const submit = (e) => {
        e.preventDefault();
        form.post('/supplier/store');
    };

    const inputCls = (err) => `w-full px-4 py-3 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-purple-300 ${err ? 'border-red-400' : 'border-gray-300'}`;

    return (
        <div className="p-6">
            <div className="flex items-center gap-3 mb-6">
                <Link href="/supplier" className="flex items-center gap-1 text-sm text-gray-600 border border-gray-300 px-3 py-2 rounded-lg hover:bg-gray-50 transition-colors">
                    <svg width="14" height="14" fill="currentColor" viewBox="0 0 16 16">
                        <path fillRule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                    </svg>
                    Back
                </Link>
                <div>
                    <h2 className="text-2xl font-bold mb-0.5">{title} Supplier</h2>
                    <p className="text-gray-500 text-sm">{title} supplier details</p>
                </div>
            </div>

            <div className="max-w-3xl">
                <div className="bg-white rounded-2xl shadow-sm p-6">
                    <form onSubmit={submit} className="space-y-4">

                        <div>
                            <label htmlFor="suppliername" className="block text-sm font-semibold mb-1">Supplier Name</label>
                            <input id="suppliername" type="text" value={form.data.suppliername} onChange={e => form.setData('suppliername', e.target.value)} placeholder="Enter supplier name" className={inputCls(form.errors.suppliername)} />
                            {form.errors.suppliername && <p className="text-red-500 text-xs mt-1">{form.errors.suppliername}</p>}
                        </div>

                        <div>
                            <label htmlFor="email" className="block text-sm font-semibold mb-1">Email</label>
                            <input id="email" type="email" value={form.data.email} onChange={e => form.setData('email', e.target.value)} placeholder="supplier@example.com" className={inputCls(form.errors.email)} />
                            {form.errors.email && <p className="text-red-500 text-xs mt-1">{form.errors.email}</p>}
                        </div>

                        <div>
                            <label htmlFor="address" className="block text-sm font-semibold mb-1">Address</label>
                            <textarea id="address" value={form.data.address} onChange={e => form.setData('address', e.target.value)} placeholder="Enter address" rows="3" className={inputCls(form.errors.address)} />
                            {form.errors.address && <p className="text-red-500 text-xs mt-1">{form.errors.address}</p>}
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label htmlFor="telno" className="block text-sm font-semibold mb-1">Tel No</label>
                                <input id="telno" type="number" value={form.data.telno} onChange={e => form.setData('telno', e.target.value)} placeholder="Tel no" className={inputCls(form.errors.telno)} />
                                {form.errors.telno && <p className="text-red-500 text-xs mt-1">{form.errors.telno}</p>}
                            </div>
                            <div>
                                <label htmlFor="cellno" className="block text-sm font-semibold mb-1">Cell No</label>
                                <input id="cellno" type="number" value={form.data.cellno} onChange={e => form.setData('cellno', e.target.value)} placeholder="Cell no" className={inputCls(form.errors.cellno)} />
                                {form.errors.cellno && <p className="text-red-500 text-xs mt-1">{form.errors.cellno}</p>}
                            </div>
                        </div>

                        <div>
                            <label htmlFor="accreditation" className="block text-sm font-semibold mb-1">Accreditation</label>
                            <input id="accreditation" type="text" value={form.data.accreditation} onChange={e => form.setData('accreditation', e.target.value)} placeholder="Accreditation" className={inputCls(form.errors.accreditation)} />
                            {form.errors.accreditation && <p className="text-red-500 text-xs mt-1">{form.errors.accreditation}</p>}
                        </div>

                        <div className="grid grid-cols-3 gap-4">
                            <div>
                                <label htmlFor="suppliertype" className="block text-sm font-semibold mb-1">Supplier Type</label>
                                <input id="suppliertype" type="number" value={form.data.suppliertype} onChange={e => form.setData('suppliertype', Number(e.target.value))} placeholder="Type ID" className={inputCls(form.errors.suppliertype)} />
                                {form.errors.suppliertype && <p className="text-red-500 text-xs mt-1">{form.errors.suppliertype}</p>}
                            </div>
                            <div>
                                <label htmlFor="comcategory" className="block text-sm font-semibold mb-1">Category</label>
                                <input id="comcategory" type="number" value={form.data.comcategory} onChange={e => form.setData('comcategory', Number(e.target.value))} placeholder="Category ID" className={inputCls(form.errors.comcategory)} />
                                {form.errors.comcategory && <p className="text-red-500 text-xs mt-1">{form.errors.comcategory}</p>}
                            </div>
                            <div>
                                <label htmlFor="payterms" className="block text-sm font-semibold mb-1">Payment Terms</label>
                                <input id="payterms" type="text" value={form.data.payterms} onChange={e => form.setData('payterms', e.target.value)} placeholder="Terms ID" className={inputCls(form.errors.payterms)} />
                                {form.errors.payterms && <p className="text-red-500 text-xs mt-1">{form.errors.payterms}</p>}
                            </div>
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label htmlFor="contactname" className="block text-sm font-semibold mb-1">Contact Name</label>
                                <input id="contactname" type="text" value={form.data.contactname} onChange={e => form.setData('contactname', e.target.value)} placeholder="Contact name" className={inputCls(form.errors.contactname)} />
                                {form.errors.contactname && <p className="text-red-500 text-xs mt-1">{form.errors.contactname}</p>}
                            </div>
                            <div>
                                <label htmlFor="designation" className="block text-sm font-semibold mb-1">Designation</label>
                                <input id="designation" type="text" value={form.data.designation} onChange={e => form.setData('designation', e.target.value)} placeholder="Designation" className={inputCls(form.errors.designation)} />
                                {form.errors.designation && <p className="text-red-500 text-xs mt-1">{form.errors.designation}</p>}
                            </div>
                        </div>

                        <div>
                            <label htmlFor="department" className="block text-sm font-semibold mb-1">Department</label>
                            <input id="department" type="text" value={form.data.department} onChange={e => form.setData('department', e.target.value)} placeholder="Department" className={inputCls(form.errors.department)} />
                            {form.errors.department && <p className="text-red-500 text-xs mt-1">{form.errors.department}</p>}
                        </div>

                        <div>
                            <label htmlFor="remarks" className="block text-sm font-semibold mb-1">Remarks</label>
                            <textarea id="remarks" value={form.data.remarks} onChange={e => form.setData('remarks', e.target.value)} placeholder="Enter remarks" rows="3" className={inputCls(form.errors.remarks)} />
                            {form.errors.remarks && <p className="text-red-500 text-xs mt-1">{form.errors.remarks}</p>}
                        </div>

                        <div className="flex gap-3 pt-2">
                            <button type="submit" className="bg-gradient-to-r from-[#667eea] to-[#764ba2] text-white px-6 py-3 rounded-lg font-semibold hover:opacity-90 transition-opacity disabled:opacity-60" disabled={form.processing}>
                                {form.processing ? 'Saving...' : `${title} Supplier`}
                            </button>
                            <Link href="/supplier" className="border border-gray-300 text-gray-700 px-6 py-3 rounded-lg font-semibold hover:bg-gray-50 transition-colors">Cancel</Link>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
}

// resources/js/Pages/Suppliers/Edit.vue
<template>
  <div class="container-fluid">
    <!-- Header -->
    <div class="mb-4">
      <div class="d-flex align-items-center mb-3">
        <Link href="/supplier" class="btn btn-outline-secondary btn-sm me-3">
          <svg width="14" height="14" fill="currentColor" viewBox="0 0 16 16" class="me-1">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
          </svg>
          Back
        </Link>
        <div>
          <h2 class="fw-bold mb-1">{{ props.title }} Supplier</h2>
          <p class="text-muted mb-0">{{ props.title }} supplier details</p>
        </div>
      </div>
    </div>

    <!-- Form Card -->
    <div class="row">
      <div class="col-lg-10">
        <div class="card border-0 shadow-sm">
          <div class="card-body p-4">
            <form @submit.prevent="submit">

              <!-- Supplier Name -->
              <div class="mb-3">
                <label for="suppliername" class="form-label fw-semibold">Supplier Name</label>
                <input
                  id="suppliername"
                  v-model="form.suppliername"
                  type="text"
                  class="form-control form-control-lg"
                  :class="{ 'is-invalid': form.errors.suppliername }"
                  placeholder="Enter supplier name"
                >
                <div v-if="form.errors.suppliername" class="invalid-feedback">
                  {{ form.errors.suppliername }}
                </div>
              </div>

              <!-- Email -->
              <div class="mb-3">
                <label for="email" class="form-label fw-semibold">Email</label>
                <input
                  id="email"
                  v-model="form.email"
                  type="email"
                  class="form-control form-control-lg"
                  :class="{ 'is-invalid': form.errors.email }"
                  placeholder="supplier@example.com"
                >
                <div v-if="form.errors.email" class="invalid-feedback">
                  {{ form.errors.email }}
                </div>
              </div>

              <!-- Address -->
              <div class="mb-3">
                <label for="address" class="form-label fw-semibold">Address</label>
                <textarea
                  id="address"
                  v-model="form.address"
                  class="form-control form-control-lg"
                  :class="{ 'is-invalid': form.errors.address }"
                  placeholder="Enter address"
                  rows="3"
                ></textarea>
                <div v-if="form.errors.address" class="invalid-feedback">
                  {{ form.errors.address }}
                </div>
              </div>

              <!-- Contact Info Row -->
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="telno" class="form-label fw-semibold">Tel No</label>
                  <input
                    id="telno"
                    v-model="form.telno"
                    type="number"
                    class="form-control form-control-lg"
                    :class="{ 'is-invalid': form.errors.telno }"
                    placeholder="Tel no"
                  >
                  <div v-if="form.errors.telno" class="invalid-feedback">
                    {{ form.errors.telno }}
                  </div>
                </div>
              </div>

              <!-- Cell Row -->
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="cellno" class="form-label fw-semibold">Cell No</label>
                  <input
                    id="cellno"
                    v-model="form.cellno"
                    type="number"
                    class="form-control form-control-lg"
                    :class="{ 'is-invalid': form.errors.cellno }"
                    placeholder="Cell no"
                  >
                  <div v-if="form.errors.cellno" class="invalid-feedback">
                    {{ form.errors.cellno }}
                  </div>
                </div>
              </div>

              <!-- Accreditation -->
              <div class="mb-3">
                <label for="accreditation" class="form-label fw-semibold">Accreditation</label>
                <input
                  id="accreditation"
                  v-model="form.accreditation"
                  type="text"
                  class="form-control form-control-lg"
                  :class="{ 'is-invalid': form.errors.accreditation }"
                  placeholder="Accreditation"
                >
                <div v-if="form.errors.accreditation" class="invalid-feedback">
                  {{ form.errors.accreditation }}
                </div>
              </div>

              <!-- Supplier Type, Category, Payment Terms Row -->
              <div class="row">
                <div class="col-md-4 mb-3">
                  <label for="suppliertype" class="form-label fw-semibold">Supplier Type</label>
                  <input
                    id="suppliertype"
                    v-model.number="form.suppliertype"
                    type="number"
                    class="form-control form-control-lg"
                    :class="{ 'is-invalid': form.errors.suppliertype }"
                    placeholder="Type ID"
                  >
                  <div v-if="form.errors.suppliertype" class="invalid-feedback">
                    {{ form.errors.suppliertype }}
                  </div>
                </div>
                <div class="col-md-4 mb-3">
                  <label for="comcategory" class="form-label fw-semibold">Category</label>
                  <input
                    id="comcategory"
                    v-model.number="form.comcategory"
                    type="number"
                    class="form-control form-control-lg"
                    :class="{ 'is-invalid': form.errors.comcategory }"
                    placeholder="Category ID"
                  >
                  <div v-if="form.errors.comcategory" class="invalid-feedback">
                    {{ form.errors.comcategory }}
                  </div>
                </div>
                <div class="col-md-4 mb-3">
                  <label for="payterms" class="form-label fw-semibold">Payment Terms</label>
                  <input
                    id="payterms"
                    v-model.number="form.payterms"
                    type="text"
                    class="form-control form-control-lg"
                    :class="{ 'is-invalid': form.errors.payterms }"
                    placeholder="Terms ID"
                  >
                  <div v-if="form.errors.payterms" class="invalid-feedback">
                    {{ form.errors.payterms }}
                  </div>
                </div>
              </div>

              <!-- Contact Name and Designation Row -->
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="contactname" class="form-label fw-semibold">Contact Name</label>
                  <input
                    id="contactname"
                    v-model="form.contactname"
                    type="text"
                    class="form-control form-control-lg"
                    :class="{ 'is-invalid': form.errors.contactname }"
                    placeholder="Contact name"
                  >
                  <div v-if="form.errors.contactname" class="invalid-feedback">
                    {{ form.errors.contactname }}
                  </div>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="designation" class="form-label fw-semibold">Designation</label>
                  <input
                    id="designation"
                    v-model="form.designation"
                    type="text"
                    class="form-control form-control-lg"
                    :class="{ 'is-invalid': form.errors.designation }"
                    placeholder="Designation"
                  >
                  <div v-if="form.errors.designation" class="invalid-feedback">
                    {{ form.errors.designation }}
                  </div>
                </div>
              </div>

              <!-- Department -->
              <div class="mb-3">
                <label for="department" class="form-label fw-semibold">Department</label>
                <input
                  id="department"
                  v-model="form.department"
                  type="text"
                  class="form-control form-control-lg"
                  :class="{ 'is-invalid': form.errors.department }"
                  placeholder="Department"
                >
                <div v-if="form.errors.department" class="invalid-feedback">
                  {{ form.errors.department }}
                </div>
              </div>

              <!-- Remarks -->
              <div class="mb-4">
                <label for="remarks" class="form-label fw-semibold">Remarks</label>
                <textarea
                  id="remarks"
                  v-model="form.remarks"
                  class="form-control form-control-lg"
                  :class="{ 'is-invalid': form.errors.remarks }"
                  placeholder="Enter remarks"
                  rows="3"
                ></textarea>
                <div v-if="form.errors.remarks" class="invalid-feedback">
                  {{ form.errors.remarks }}
                </div>
              </div>

              <!-- Buttons -->
              <div class="d-flex gap-2">
                <button
                  type="submit"
                  class="btn btn-primary btn-lg"
                  :disabled="form.processing"
                >
                  <span v-if="form.processing" class="spinner-border spinner-border-sm me-2"></span>
                  {{ form.processing ? 'Creating...' : 'Create Supplier' }}
                </button>
                <Link href="/supplier" class="btn btn-outline-secondary btn-lg">
                  Cancel
                </Link>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { useForm, Link } from '@inertiajs/vue3';

const props =defineProps({
  title: String,
  supplier: Object,
});

const form = useForm(props.supplier ? {
  suppliername: props.supplier.suppliername || '',
  email: props.supplier.email || '',
  address: props.supplier.address || '',
  telno: props.supplier.telno || '',
  cellno: props.supplier.cellno || '',
  accreditation: props.supplier.accreditation || '',
  suppliertype: props.supplier.suppliertype || '',
  comcategory: props.supplier.comcategory || '',
  payterms: props.supplier.payterms || '',
  contactname: props.supplier.contactname || '',
  designation: props.supplier.designation || '',
  department: props.supplier.department || '',
  remarks: props.supplier.remarks || '',
} : {
  suppliername: '',
  email: '',
  address: '',
  telno: '',
  cellno: '',
  accreditation: '',
  suppliertype: '',
  comcategory: '',
  payterms: '',
  contactname: '',
  designation: '',
  department: '',
  remarks: '',
} );

const submit = () => {
  form.post('/supplier/store');
};
</script>

<style scoped>
.form-control-lg {
  padding: 0.75rem 1rem;
  font-size: 1rem;
  border-radius: 0.5rem;
}

.form-control:focus,
.form-control:focus-visible {
  border-color: #2563eb;
  box-shadow: 0 0 0 0.2rem rgba(37, 99, 235, 0.25);
}

.btn-lg {
  padding: 0.75rem 1.5rem;
  font-size: 1rem;
  border-radius: 0.5rem;
}
</style>
