// resources/js/Pages/Companies/Create.jsx
import { useForm, Link } from '@inertiajs/react';

export default function CompanyCreate({ company }) {
    const form = useForm({
        id: company?.id || null,
        companyname: company?.companyname || '',
        email: company?.email || '',
        address: company?.address || '',
        phone: company?.phone || '',
        fax: company?.fax || '',
        website: company?.website || '',
        logo: company?.logo || '',
    });

    const submit = (e) => {
        e.preventDefault();
        form.post('/company/store', { onSuccess: () => form.reset() });
    };

    const inputCls = (err) => `w-full px-4 py-3 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-purple-300 ${err ? 'border-red-400' : 'border-gray-300'}`;

    return (
        <div className="p-6">
            <div className="mb-6">
                <h2 className="text-2xl font-bold mb-1">Create/Update Company</h2>
                <p className="text-gray-500">Add a new company to the system</p>
            </div>
            <div className="max-w-2xl">
                <div className="bg-white rounded-2xl shadow-sm p-6">
                    <form onSubmit={submit} className="space-y-4">
                        {[
                            { id: 'companyname', label: 'Company Name', type: 'text', req: true, val: form.data.companyname, set: 'companyname', err: form.errors.companyname, ph: 'Enter company name' },
                            { id: 'address', label: 'Address', type: 'text', req: true, val: form.data.address, set: 'address', err: form.errors.address, ph: 'Enter company address' },
                            { id: 'phone', label: 'Phone', type: 'tel', req: true, val: form.data.phone, set: 'phone', err: form.errors.phone, ph: 'Enter phone number' },
                            { id: 'email', label: 'Email Address', type: 'email', req: true, val: form.data.email, set: 'email', err: form.errors.email, ph: 'user@example.com' },
                            { id: 'website', label: 'Website', type: 'text', req: false, val: form.data.website, set: 'website', err: form.errors.website, ph: 'https://www.example.com', opt: true },
                            { id: 'logo', label: 'Logo URL', type: 'text', req: false, val: form.data.logo, set: 'logo', err: form.errors.logo, ph: 'https://www.example.com/logo.png' },
                        ].map(f => (
                            <div key={f.id}>
                                <label htmlFor={f.id} className="block text-sm font-semibold mb-1">
                                    {f.label}
                                    {f.req && <span className="text-red-500 ml-1">*</span>}
                                    {f.opt && <span className="text-gray-400 font-normal ml-1">optional</span>}
                                </label>
                                <input
                                    id={f.id}
                                    type={f.type}
                                    value={f.val}
                                    onChange={e => form.setData(f.set, e.target.value)}
                                    placeholder={f.ph}
                                    className={inputCls(f.err)}
                                    required={f.req}
                                />
                                {f.err && <p className="text-red-500 text-xs mt-1">{f.err}</p>}
                            </div>
                        ))}
                        <div className="flex gap-3 pt-2">
                            <button type="submit" className="bg-gradient-to-r from-[#667eea] to-[#764ba2] text-white px-6 py-3 rounded-lg font-semibold hover:opacity-90 transition-opacity disabled:opacity-60" disabled={form.processing}>
                                {form.processing ? 'Creating...' : 'Create Company'}
                            </button>
                            <Link href="/companies" className="border border-gray-300 text-gray-700 px-6 py-3 rounded-lg font-semibold hover:bg-gray-50 transition-colors">Cancel</Link>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
}

// resources/js/Pages/Companies/Create.vue
<template>
        <div class="container-fluid">
            <!-- Header -->
            <div class="mb-4">
                <div class="d-flex align-items-center mb-3">
                    <div>
                        <h2 class="fw-bold mb-1">Create/Update Company</h2>
                        <p class="text-muted mb-0">Add a new company to the system</p>
                    </div>
                </div>
            </div>

            <!-- Form Card -->
            <div class="row">
                <div class="col-lg-8">
                    <div class="card border-0 shadow-sm">
                        <div class="card-body p-4">
                            <form @submit.prevent="submit">
                                <!-- Company Name -->
                                <div class="mb-3">
                                    <label for="companyname" class="form-label fw-semibold">Company Name <span class="text-danger ms-1">*</span></label>
                                    <input
                                        id="companyname"
                                        v-model="form.companyname"
                                        type="text"
                                        class="form-control form-control-lg"
                                        :class="{ 'is-invalid': form.errors.companyname }"
                                        placeholder="Enter company name"
                                        required
                                    >
                                    <div v-if="form.errors.companyname" class="invalid-feedback">
                                        {{ form.errors.companyname }}
                                    </div>
                                </div>

                                    <!-- Address -->
                                <div class="mb-3">
                                    <label for="address" class="form-label fw-semibold">Address<span class="text-danger ms-1">*</span></label>
                                    <input
                                        id="address"
                                        v-model="form.address"
                                        type="text"
                                        class="form-control form-control-lg"
                                        :class="{ 'is-invalid': form.errors.address }"
                                        placeholder="Enter company address"
                                    >
                                    <div v-if="form.errors.address" class="invalid-feedback">
                                        {{ form.errors.address }}
                                    </div>
                                </div>

                                    <!-- Phone -->
                                <div class="mb-3">
                                    <label for="phone" class="form-label fw-semibold">Phone<span class="text-danger ms-1">*</span></label>
                                    <input
                                        id="phone"
                                        v-model="form.phone"
                                        type="tel"
                                        class="form-control form-control-lg"
                                        :class="{ 'is-invalid': form.errors.phone }"
                                        placeholder="Enter company phone number"
                                    >
                                    <div v-if="form.errors.phone" class="invalid-feedback">
                                        {{ form.errors.phone }}
                                    </div>
                                </div>

                                <!-- Email -->
                                <div class="mb-3">
                                    <label for="email" class="form-label fw-semibold">Email Address <span class="text-danger ms-1">*</span></label>
                                    <input
                                        id="email"
                                        v-model="form.email"
                                        type="email"
                                        class="form-control form-control-lg"
                                        :class="{ 'is-invalid': form.errors.email }"
                                        placeholder="user@example.com"
                                        required
                                    >
                                    <div v-if="form.errors.email" class="invalid-feedback">
                                        {{ form.errors.email }}
                                    </div>
                                </div>

                                <!-- Website -->
                                <div class="mb-3">
                                    <label for="website" class="form-label fw-semibold">Website<span class="text-muted ms-1">optional</span></label>
                                    <input  
                                        id="website"
                                        v-model="form.website"
                                        type="text"
                                        class="form-control form-control-lg"
                                        :class="{ 'is-invalid': form.errors.website }"
                                        placeholder="https://www.example.com"
                                    >
                                    <div v-if="form.errors.website" class="invalid-feedback">
                                        {{ form.errors.website }}
                                    </div>
                                </div>

                                <!-- Logo -->
                                <div class="mb-3">
                                    <label for="logo" class="form-label fw-semibold">Logo URL</label>
                                    <input
                                        id="logo"
                                        v-model="form.logo"
                                        type="text"
                                        class="form-control form-control-lg"
                                        :class="{ 'is-invalid': form.errors.logo }"
                                        placeholder="https://www.example.com/logo.png"
                                    >
                                    <div v-if="form.errors.logo" class="invalid-feedback">
                                        {{ form.errors.logo }}
                                    </div>
                                </div>

                                <!-- Buttons -->
                                <div class="d-flex gap-2">
                                    <button
                                        type="submit"
                                        class="btn btn-primary btn-lg"
                                        :disabled="form.processing"
                                    >
                                        <span v-if="form.processing" class="spinner-border spinner-border-sm me-2"></span>
                                        {{ form.processing ? 'Creating...' : 'Create Company' }}
                                    </button>
                                    <Link href="/companies" class="btn btn-outline-secondary btn-lg">
                                        Cancel
                                    </Link>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</template>

<script setup>
import { useForm, Link } from '@inertiajs/vue3';
import LayoutAuthenticated from '@/Layouts/LayoutAuthenticated.vue';

const props = defineProps({
    company: Object,
});

const form = useForm({
    id: props.company?.id || null,
    companyname: props.company?.companyname || '',
    email: props.company?.email || '',
    address: props.company?.address || '',
    phone: props.company?.phone || '',
    fax: props.company?.fax || '',
    website: props.company?.website || '',
    logo: props.company?.logo || '',
   
});

const submit = () => {
    form.post('/company/store', {
        onSuccess: () => {
            form.reset();
        },
    });
};
</script>

<style scoped>
.form-control-lg {
    padding: 0.75rem 1rem;
    font-size: 1rem;
    border-radius: 0.5rem;
}

.form-control:focus {
    border-color: #2563eb;
    box-shadow: 0 0 0 0.2rem rgba(37, 99, 235, 0.25);
}

.btn-lg {
    padding: 0.75rem 1.5rem;
    font-size: 1rem;
    border-radius: 0.5rem;
}
</style>
